import { ICommandHandler } from '../command';

export const moveLeft: ICommandHandler = async serviceRegistry => {};
export const moveRight: ICommandHandler = async serviceRegistry => {};
export const moveUp: ICommandHandler = async serviceRegistry => {};
export const moveDown: ICommandHandler = async serviceRegistry => {};
export const moveLeftByWord: ICommandHandler = async serviceRegistry => {};
export const moveRightByWord: ICommandHandler = async serviceRegistry => {};
export const moveToLineLeft: ICommandHandler = async serviceRegistry => {};
export const moveToLineRight: ICommandHandler = async serviceRegistry => {};
export const moveToDocStart: ICommandHandler = async serviceRegistry => {};
export const moveToDocEnd: ICommandHandler = async serviceRegistry => {};
export const moveHeadLeft: ICommandHandler = async serviceRegistry => {};
export const moveHeadRight: ICommandHandler = async serviceRegistry => {};
export const moveHeadUp: ICommandHandler = async serviceRegistry => {};
export const moveHeadDown: ICommandHandler = async serviceRegistry => {};
export const moveHeadLeftByWord: ICommandHandler = async serviceRegistry => {};
export const moveHeadRightByWord: ICommandHandler = async serviceRegistry => {};
export const moveHeadToLineLeft: ICommandHandler = async serviceRegistry => {};
export const moveHeadToLineRight: ICommandHandler = async serviceRegistry => {};
export const moveHeadToDocStart: ICommandHandler = async serviceRegistry => {};
export const moveHeadToDocEnd: ICommandHandler = async serviceRegistry => {};
export const selectAll: ICommandHandler = async serviceRegistry => {};
