version: 2
jobs:
  build:
    docker:
      - image: node:12
    working_directory: /tmp/taleweaver
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "packages/core/package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            cd packages/core
            npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "packages/core/package-lock.json" }}
      - run:
          name: Build
          command: |
            cd packages/core
            npm run build
workflows:
  version: 2
  build:
    jobs:
      - build
