import type { Style } from "./style";
import type { ComputedStyle } from "./computed-style";

export interface PropertyMeta {
  readonly inherits: boolean;
}

/** Per-property metadata: whether the property inherits from parent. */
export const PROPERTY_META: { readonly [K in keyof Required<Style>]: PropertyMeta } = {
  // Inherits = true
  fontFamily:        { inherits: true  },
  fontSize:          { inherits: true  },
  fontWeight:        { inherits: true  },
  fontStyle:         { inherits: true  },
  textDecoration:    { inherits: true  },
  lineHeight:        { inherits: true  },
  color:             { inherits: true  },
  whiteSpace:        { inherits: true  },
  listStyleType:     { inherits: true  },
  listStylePosition: { inherits: true  },
  widows:            { inherits: true  },
  orphans:           { inherits: true  },

  // Inherits = false
  display:           { inherits: false },
  width:             { inherits: false },
  height:            { inherits: false },
  minWidth:          { inherits: false },
  minHeight:         { inherits: false },
  maxWidth:          { inherits: false },
  maxHeight:         { inherits: false },
  boxSizing:         { inherits: false },
  marginTop:         { inherits: false },
  marginRight:       { inherits: false },
  marginBottom:      { inherits: false },
  marginLeft:        { inherits: false },
  paddingTop:        { inherits: false },
  paddingRight:      { inherits: false },
  paddingBottom:     { inherits: false },
  paddingLeft:       { inherits: false },
  borderTopWidth:    { inherits: false },
  borderRightWidth:  { inherits: false },
  borderBottomWidth: { inherits: false },
  borderLeftWidth:   { inherits: false },
  borderTopStyle:    { inherits: false },
  borderRightStyle:  { inherits: false },
  borderBottomStyle: { inherits: false },
  borderLeftStyle:   { inherits: false },
  borderTopColor:    { inherits: false },
  borderRightColor:  { inherits: false },
  borderBottomColor: { inherits: false },
  borderLeftColor:   { inherits: false },
  backgroundColor:   { inherits: false },
  verticalAlign:     { inherits: false },
  float:             { inherits: false },
  clear:             { inherits: false },
  breakBefore:       { inherits: false },
  breakAfter:        { inherits: false },
  breakInside:       { inherits: false },
};

/** CSS-faithful initial computed values for every property. */
export const INITIAL_COMPUTED_STYLE: ComputedStyle = {
  display:           "inline",
  width:             "auto",
  height:            "auto",
  minWidth:          0,
  minHeight:         0,
  maxWidth:          "none",
  maxHeight:         "none",
  boxSizing:         "content-box",
  marginTop:         0,
  marginRight:       0,
  marginBottom:      0,
  marginLeft:        0,
  paddingTop:        0,
  paddingRight:      0,
  paddingBottom:     0,
  paddingLeft:       0,
  borderTopWidth:    0,
  borderRightWidth:  0,
  borderBottomWidth: 0,
  borderLeftWidth:   0,
  borderTopStyle:    "none",
  borderRightStyle:  "none",
  borderBottomStyle: "none",
  borderLeftStyle:   "none",
  borderTopColor:    "black",
  borderRightColor:  "black",
  borderBottomColor: "black",
  borderLeftColor:   "black",
  backgroundColor:   "transparent",
  fontFamily:        "system-ui",
  fontSize:          16,
  fontWeight:        "normal",
  fontStyle:         "normal",
  textDecoration:    "none",
  lineHeight:        1.2,
  color:             "black",
  whiteSpace:        "normal",
  verticalAlign:     "baseline",
  float:             "none",
  clear:             "none",
  breakBefore:       "auto",
  breakAfter:        "auto",
  breakInside:       "auto",
  widows:            2,
  orphans:           2,
  listStyleType:     "disc",
  listStylePosition: "outside",
};
